image: Visual Studio 2017

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 --sonarLogin=%sonartoken% --nugetApiKey=%nugetApiKey%

# Tests
test: off
  
skip_commits:
  files:
    - '.github/'
    - '**/*.md'

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:   
- tools -> build.cake
