name: Build and release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Cake Action
      uses: cake-build/cake-action@v1.1.1
      with:
        verbosity: Verbose
        cake-version: 0.38.0
