name: Build (and release)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v7
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Get the sources
        uses: actions/checkout@v4
        
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow      
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
          
      - name: Run Cake script
        uses: cake-build/cake-action@v2
        with:
          target: Default
          cake-version: tool-manifest
          verbosity: Diagnostic
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN_SECURITYTXT }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
