name: Build (and release)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x        
          
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          
      - name: Run Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Verbose
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN_SECURITYTXT }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
